### ISSUE TITLE
not support this "#{a} #{a}".format( {a: 'hello'} )

### ISSUE THREAD

**Issue by mkatsoho** [tmaeda1981jp/string-format-js#3]
I made a fix on this for your reference

$ git diff format.js
diff --git a/format.js b/format.js
index 6b50e4c..0a6f0f2 100644
--- a/format.js
+++ b/format.js
@@ -244,8 +244,19 @@

```
   if (args.length === 1 && typeof args[0] === 'object') {
     for (i=0; i < Object.keys(args[0]).length; i+=1) {
```
-          if (result.match(/(#{\w+})/)) {
  +
-          // New feature: handle such scenario - the string has multiple (not only one) of a single hash key
-          // NOTE: using '_2' not '_1' in case such senario like {a: '#{b}', b: 'value'}, or like {a: '#{b} #{c}'}
-          var loopMax = result.match((/(#{\w+})/g));
-          var loopMax = loopMax ? loopMax.length \* 2 : 0;  // TODO, let end-user can change 2 to any number
-          //SKIP TEST:          var loopMax = 3;   // TODO hardcoded, for testing only
  +
-          var loopInd = 0;
-          while (result.match(/(#{\w+})/)) {
-            if (loopInd >= loopMax) { break; }
-            // SKIP console.log('args[i] with i = ', i, 'loop# =', loopInd, ', handling key =', (result.match(/(#{\w+})/))['0'] );  // TODO debug log for testing
           result = new Formatter(RegExp.$1).format(result, args[0]);
-            loopInd ++;  
         }
       }
     }

**Comment by tmaeda1981jp** [comment]
Thanks for reporting. Fixed.
